Repository wecode-bootcamp-korea/27-2nd-SUULGO-frontend, pull requests merged in 2021-12, with the labels that each got.

#1 [27기 오동녘어진이] theme 파일에 mixin 추가
  package-lock.json
  package.json
  src/styles/theme.js
Labels: Status: 리뷰 요청

#6 [27기 구유진] 멘토 리뷰 반영 / Add: 공통API 상수데이터 추가
  .gitignore
  src/config.js
Labels: Status: 리뷰 요청

#4 [27기 오동녘어진이] 상세 페이지와 상세 페이지에서 연결되는 모달창 레이아웃 구현.
  .gitignore
  package-lock.json
  package.json
  public/data/userData.json
  public/images/mangorookie.jpeg
  src/components/RequestModal/RequestModal.js
  src/pages/Detail/Detail.js
  src/pages/Detail/tagListData.js
Labels: Status: Accepted

#2 [27기 구유진] 멘토리뷰 반영 / nav바 레이아웃 + css 소셜로그인 완성
  package-lock.json
  public/data/loginData.json
  public/images/profile.png
  public/images/suulgolog.png
  public/index.html
  src/components/Nav/AfterLogin/AfterLogin.js
  src/components/Nav/BeforeLogin/BeforeLogin.js
  src/components/Nav/Nav.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#9 [27기 오동녘어진이] 술 관련 태그들 분리해서 관리되도록 컴포넌트로 분리.
  package-lock.json
  src/components/MatchTagWrapper/MatchTagWrapper.js
  src/components/MatchTagWrapper/tagListData.js
  src/pages/Detail/Detail.js
Labels: Status: Accepted

#10 [27기 구유진] Add: nav css 변경
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#8 [27기 오동녘어진이] ADD : my page 리뷰 반영 및 conflict 해결
  package-lock.json
  public/data/userData.json
  src/components/MatchTagWrapper/MatchTagWrapper.js
  src/pages/Detail/Detail.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/myPageList.js
  src/utils.js
Labels: Status: 리뷰 요청

#11 [27기 오동녘어진이] ADD : 모달창에서 약속 잡기 기능 추가
  src/components/RequestModal/RequestModal.js
  src/pages/Detail/Detail.js
  src/utils.js
Labels: Status: 리뷰 요청

#14 [27기 오동녘어진이] ADD : 약속잡기 기능에서 서버 주소 추가
  src/components/RequestModal/RequestModal.js
  src/config.js
Labels: Status: 리뷰 요청

#7 [27기 김재호]리스트페이지 Modify : 리뷰 요청 수정(추가기능 구현중)
  public/data/mockdata.json
  public/images/술이원수.jpg
  public/images/스인.jpg
  public/images/스쳐도인연.jpg
  public/images/취하고싶은밤.jpg
  src/pages/List/Icon.js
  src/pages/List/IconComponent.js
  src/pages/List/IconData.js
  src/pages/List/IconGroup.js
  src/pages/List/List.js
  src/pages/List/ListMainCard.js
Labels: Status: 리뷰 요청

#5 [27기 김재호]메인페이지 컴플릭트 해결완료
  public/images/술주정.jpg
  src/pages/Main/Icons.js
  src/pages/Main/Main.js
  src/utils.js
Labels: Status: 리뷰 요청

#16 [27기 오동녘어진이] ADD : detail page에서 path parameter를 통해 동적 라우팅 구현
  src/Router.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/tagListData.js
Labels: Status: 리뷰 요청

#12 [27기 구유진] Add: survey 필수기능 완성
  package-lock.json
  package.json
  src/pages/Survey/Description.js
  src/pages/Survey/Question/FreeQuestion.js
  src/pages/Survey/Question/NumberQuestion.js
  src/pages/Survey/Question/PluralQuestion.js
  src/pages/Survey/Question/Question.js
  src/pages/Survey/Question/SingleQuestion.js
  src/pages/Survey/Survey.js
  src/pages/data/surveyData.js
  src/utils.js
Labels: Status: 리뷰 요청

#18 [27기 구유진] Add: 서베이유무의 분기처리 기능 구현
  src/components/Nav/BeforeLogin/BeforeLogin.js
  src/config.js
Labels: Status: 리뷰 요청

#20 [27기 구유진] Modify: freeValue 입력시 유효성검사 수정
  src/components/Nav/AfterLogin/AfterLogin.js
  src/components/Nav/BeforeLogin/BeforeLogin.js
  src/config.js
  src/pages/Survey/Survey.js
Labels: Status: 리뷰 요청

#22 [27기 구유진] 리스트페이지 css수정
  src/pages/List/List.js
  src/pages/List/ListMainCard.js
Labels: Status: 리뷰 요청

#25 Add: 옵션선택 유무 워닝메시지 추가
  src/pages/Survey/Survey.js
Labels: Status: 추가 기능 구현중
